#ifndef BINDING_STUBS_H
#define BINDING_STUBS_H

#define GEODE_FRIEND_MODIFY
#define GEODE_CUSTOM_CONSTRUCTOR_BEGIN(Class_)
#define GEODE_CUSTOM_CONSTRUCTOR_COCOS(Class_, Base_)
#define GEODE_CUSTOM_CONSTRUCTOR_GD(Class_, Base_)
#define GEODE_ZERO_CONSTRUCTOR_BEGIN(Class_)
#define GEODE_ZERO_CONSTRUCTOR(Class_, Base_)
#define GEODE_CUTOFF_CONSTRUCTOR_BEGIN(Class_)
#define GEODE_CUTOFF_CONSTRUCTOR_COCOS(Class_, Base_)
#define GEODE_CUTOFF_CONSTRUCTOR_GD(Class_, Base_)
#define GEODE_FILL_CONSTRUCTOR(Class_, Offset_)

#define GEODE_DLL
#define GEODE_NONINHERITED_MEMBERS

#endif
